name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Crystal lang
        run: |
          sudo apt-get update
          sudo apt-get install crystal

      - name: Test
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          make test
