name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          set -eo pipefail
          download_url="$(curl -Ls https://api.github.com/repos/linz/action-git-version/releases/latest | jq -r .assets[0].browser_download_url)"
          curl -Ls "$download_url" > /usr/local/bin/git-version
          chmod +x /usr/local/bin/git-version

      - id: previous-version
        shell: bash
        run: |
          set -eo pipefail

          PREVIOUS_VERSION=$(git-version \
              --previous-version \
              --release-branch "master" \
              --dev-branch "" \
              --minor-identifier="feat:" \
              --major-identifier="BREAKING CHANGE:" \
              --version-prefix "v" \
              --version-suffix "")
